#!/system/bin/sh

target=`cat /sys/devices/system/cpu/cpu0/cpufreq/scaling_governor`
case $target in
interactive)
  echo "20000 1400000:40000 1700000:20000" > /sys/devices/system/cpu/cpufreq/interactive/above_hispeed_delay
  echo 90 > /sys/devices/system/cpu/cpufreq/interactive/go_hispeed_load
  echo 1497600 > /sys/devices/system/cpu/cpufreq/interactive/hispeed_freq
  echo 40000 > /sys/devices/system/cpu/cpufreq/interactive/min_sample_time
  echo 100000 > /sys/devices/system/cpu/cpufreq/interactive/sampling_down_factor
  echo 1036800 > /sys/devices/system/cpu/cpufreq/interactive/sync_freq
  echo "85 1500000:90 1800000:70" > /sys/devices/system/cpu/cpufreq/interactive/target_loads
  echo 1190400 > /sys/devices/system/cpu/cpufreq/interactive/up_threshold_any_cpu_freq
  echo 60 > /sys/devices/system/cpu/cpufreq/interactive/up_threshold_any_cpu_load
  ;;
esac
